# Generated by Django 4.1.6 on 2023-02-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=60)),
                ('id_no', models.CharField(max_length=30)),
                ('course_id', models.CharField(max_length=20)),
                ('course_name', models.TextField(max_length=200)),
                ('Course_code', models.CharField(max_length=20)),
            ],
        ),
    ]
