# Generated by Django 4.1.6 on 2023-02-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Admin_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_admin',
            new_name='Student_administration',
        ),
    ]
